### PR TITLE
Response: check AuthnContextClassRef value; fix test 97

### PR DESCRIPTION
**Pull request by ctrlaltca**
Please see #105 first for an introduction on this PR.
This PR contains a fix for the check on the following test:
 97. Elemento AuthContextClassRef impostato ad un valore non previsto.

### CODE REVIEW

**Comment by simevo** [comment]
The proposed changes LGTM. I have one formal objection:
- Please change the base branch to `develop` as we are trying to adhere to git flow.

**Comment by ctrlaltca** [comment]
Done, thank you

**Comment by simevo** [comment]
Please rebase on current develop, thanks

**Comment by ctrlaltca** [comment]
Rebased, thank you

**Pull request merged**
